import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Layout from "../components/Layout";
import Header from "../components/Header";
import team from "../public/team.svg";
import { Zoom, Bounce } from "react-reveal";
const Home: NextPage = () => {
  const services = [
    {
      title: "Web Development",
      desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque minima exercitationem repellendus fuga quam laboriosam hic aut harum veniam aliquid.",
    },
    {
      title: "App Development",
      desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque minima exercitationem repellendus fuga quam laboriosam hic aut harum veniam aliquid.",
    },
    {
      title: "SaaS Development",
      desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloremque minima exercitationem repellendus fuga quam laboriosam hic aut harum veniam aliquid.",
    },
  ];
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout>
        {/* <Header /> */}
        <section
          className="min-h-[calc(100vh-64px)] px-6 mb-0 pb-0 w-full bg-[#1a1a1a]"
          id="Home"
        >
          <div className="md:flex md:items-center md:justify-between md:w-full px-3 pt-8">
            <div className="pt-5 md:pt-0 md:w-6/12 ">
              <h3 className="font-extrabold text-4xl md:text-7xl text-white">
                Athena
              </h3>
              <Bounce>
                <h3 className="font-extrabold text-4xl md:text-7xl text-transparent bg-clip-text bg-gradient-to-r from-purple-600 to-pink-600">
                  Dev Team
                </h3>
              </Bounce>
              <p className="text-white font-thin text-xl mb-4">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Unde
                neque, obcaecati ratione, temporibus doloribus, expedita
                corporis eum debitis tempora repudiandae modi!
              </p>
              <div className="flex mb-10 md:mb-0 w-5/6">
                <button
                  onClick={() => router.push("/signup")}
                  className="hover:scale-105 bg-gradient-to-r from-purple-600 to-pink-600  text-white p-3 font-bold rounded-sm mr-1 border-none w-full"
                >
                  Get Quote
                </button>
                {/* <button className=" bg-primary text-white p-3 font-bold rounded-sm border-none w-6/12">
                Sign Up
              </button> */}
              </div>
            </div>

            <Image className=" md:w-6/12 z-0" src={team} alt="illustration" />
          </div>
        </section>
        <section className="p-6  w-full bg-white" id="About">
          <h3 className=" text-center text-2xl text-gray-600 font-extrabold">
            Services we can help you with
          </h3>
          <div className="md:flex ">
            {services.map((item, index) => (
              <Zoom key={index}>
                <div className="bg-white shadow m-2 flex flex-col p-3 rounded-sm items-center">
                  <h2 className="text-slate-900">{item.title}</h2>
                  <h3 className="text-slate-900">{item.desc}</h3>
                </div>
              </Zoom>
            ))}
          </div>
          <p className="text-center mb-10 font-light">
            Your brand wasn’t built to be hidden. Help it stand out with branded
            links that drive more clicks.
          </p>
        </section>

        <section
          className="w-full bg-slate-900 h-60 flex flex-col items-center justify-center"
          id="FAQs"
        >
          <h3 className=" text-center text-4xl text-white font-extrabold mb-7">
            More than a free link shortener
          </h3>

          <button
            onClick={() => router.push("/signup")}
            className=" bg-primary text-white p-3 font-bold rounded-sm mr-1 border-none"
            id="FAQs"
          >
            Start for free
          </button>
        </section>
        <section className="p-6 w-full mb-6"></section>
        <section className="w-full p-6  bg-slate-900 flex flex-col items-center justify-center">
          <h3 className=" text-center text-2xl text-white font-extrabold mb-3">
            Quick Links
          </h3>

          <div className="my-3 text-center">
            <p className="font-thin text-white text-sm">Privacy Policy</p>
            <p className="font-thin text-sm text-white">
              Copyright © 2021 Solomon. All Rights Reserved.
            </p>
          </div>
        </section>
      </Layout>
    </div>
  );
};

export default Home;
